pipeline {
    agent any
 
    tools { 
      maven 'MAVEN_HOME'
    }
    
      stages {
        
        stage('Test') {
            steps {
                bat "mvn -D clean test -f ApiAutomation"
                
            }
            
           
            
 
            post {                
               
                always {
                   echo "Report"
                  archiveArtifacts artifacts: 'Reports/index.html', followSymlinks: false
                }
            }
        }
    }
   }
